version: "3"
services:
  app:
    image: node:14-alpine
    environment:
      - TZ=America/Argentina/Mendoza
    working_dir: /app
    volumes:
      - .:/app
    command: npm deploy
    ports:
      - "8000:8000"
    restart:  always
